# Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
# 根地址 根nginx配置location保持一致
#server.basePath: "/elk"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
#i18n.locale: "zh-CN"